package testcases;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import base.BaseTest;



public class NewCampoTest extends BaseTest {
	/*
	 * public WebDriver driver; // private Map<String, Object> vars;
	 * JavascriptExecutor js;
	 * 
	 * @BeforeTest public void setUp() { driver = new ChromeDriver(); js =
	 * (JavascriptExecutor) driver; // vars = new HashMap<String, Object>(); }
	 * 
	 * @AfterTest public void tearDown() { driver.quit(); }
	 */

	@Test
	public void newCampo() {
		// Test name: NewCampo
		// Step # | name | target | value
		// 1 | open | /login |
		driver.get("https://campo.nationalguard.com/login");
		// 2 | setWindowSize | 1936x1056 |
		driver.manage().window().setSize(new Dimension(1936, 1056));
		// 3 | type | id=email | rakesh.shrestha@iostudio.com
		driver.findElement(By.id("email")).sendKeys("rakesh.shrestha@iostudio.com");
		// 4 | click | id=password |
		driver.findElement(By.id("password")).click();
		// 5 | type | id=password | Ma428368#$ma
		driver.findElement(By.id("password")).sendKeys("Ma428368#$ma");
		// 6 | click | css=.primary-btn |
		driver.findElement(By.cssSelector(".primary-btn")).click();
		// 7 | click | css=.list-group-item:nth-child(2) > span |
		driver.findElement(By.cssSelector(".list-group-item:nth-child(2) > span")).click();

		// Date to choose gives current date
		Date date = new Date();
		System.out.println(date);

		// Constructs a SimpleDateFormat using the given pattern
		SimpleDateFormat formattedDate = new SimpleDateFormat("yyyyMMdd");

		// Formats a Date into a date/time string.
		formattedDate = new SimpleDateFormat("ddhhmmss");
		String day = formattedDate.format(date);
		// 8 | click | id=campaignName |
		driver.findElement(By.id("campaignName")).click();
		// 9 | type | id=campaignName | wapstrx + dayHourMinuteSeconds
		driver.findElement(By.id("campaignName")).sendKeys("wapstrx" + day);

		// 10 | click | id=campaignDescription |
		driver.findElement(By.id("campaignDescription")).click();
		// 11 | type | id=campaignDescription | Test
		driver.findElement(By.id("campaignDescription")).sendKeys("Test");

		// 12 | click | id=startDate | Enter todays date
		driver.findElement(By.id("startDate")).click();
		// Get day from Date
		String dayStart = new SimpleDateFormat("d").format(date);
		// Start Date Select
		driver.findElement(By.xpath("//*[text()=" + dayStart + "]")).click();
		

		// 14 | click | id=endDate |
		driver.findElement(By.id("endDate")).click();

		//Choosing End Date 
		// Gets a calendar using the default time zone and locale
		Calendar cal = Calendar.getInstance();

		// Adds or subtracts the specified amount of time to the given calendar
		// field,based on the calendar's rules
		cal.add(Calendar.DATE, 15); // number of days to add 

		// New Date after adding 1 day
		date = cal.getTime();
		System.out.println(date);

		// Extract Month and Year
		String month = new SimpleDateFormat("MMMM").format(date);
		String year = new SimpleDateFormat("yyyy").format(date);
		// Get Day from Date
		String dayEnd = new SimpleDateFormat("d").format(date);

		// Click on Return Calendar
		driver.findElement(By.id("returnCalendar")).click();

		String monthYearToBeSelected = month + " " + year;
		System.out.println("Month and Year to be selected:   " + monthYearToBeSelected);

		// Choose the end date by checking month year displayed
		while (true) {
			String monthyearDisplayed = driver.findElement(By.xpath("//div[@class='DayPicker-Caption']")).getText();
			System.out.println("Month year displayed on the calender:   " + monthyearDisplayed);

			if (monthYearToBeSelected.equalsIgnoreCase(monthyearDisplayed)) {
				// select date
				driver.findElement(By.xpath("//*[text()=" + dayEnd + "]")).click();
				break;

			}

			else {
				// click on next button to go to next month
				driver.findElement(By.xpath(" //span[@class='DayPicker-NavButton DayPicker-NavButton--next']")).click();
				
			}

		}

		// 17 | click | css=.info-message > .primary-btn |
		driver.findElement(By.cssSelector(".info-message > .primary-btn")).click();
		// 18 | click | css=.mb-4 > .secondary-btn:nth-child(2) |
		driver.findElement(By.cssSelector(".mb-4 > .secondary-btn:nth-child(2)")).click();
		// 19 | click | css=.w-49:nth-child(1) |
		driver.findElement(By.cssSelector(".w-49:nth-child(1)")).click();
		// 20 | select | css=.w-49:nth-child(1) | label=Web
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".w-49:nth-child(1)"));
			dropdown.findElement(By.xpath("//option[. = 'Web']")).click();
		}
		// 21 | click | css=.w-49:nth-child(1) |
		driver.findElement(By.cssSelector(".w-49:nth-child(1)")).click();
		// 22 | click | css=.d-flex:nth-child(2) |
		driver.findElement(By.cssSelector(".d-flex:nth-child(2)")).click();
		// 23 | select | css=.d-flex:nth-child(2) | label=Billboard
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".d-flex:nth-child(2)"));
			dropdown.findElement(By.xpath("//option[. = 'Billboard']")).click();
		}
		// 24 | click | css=.d-flex:nth-child(2) |
		driver.findElement(By.cssSelector(".d-flex:nth-child(2)")).click();
		// 25 | click | id=newTrackingName |
		driver.findElement(By.id("newTrackingName")).click();
		// 26 | type | id=newTrackingName | Billboard
		driver.findElement(By.id("newTrackingName")).sendKeys("Billboard");
		// 27 | click | id=newTrackingDescription |
		driver.findElement(By.id("newTrackingDescription")).click();
		// 28 | type | id=newTrackingDescription | Web
		driver.findElement(By.id("newTrackingDescription")).sendKeys("Web");
		// 29 | click | name=target_url |
		driver.findElement(By.name("target_url")).click();
		// 30 | select | name=target_url | label=https://nationalguard.com/
		{
			WebElement dropdown = driver.findElement(By.name("target_url"));
			dropdown.findElement(By.xpath("//option[. = 'https://nationalguard.com/']")).click();
		}
		// 31 | click | name=target_url |
		driver.findElement(By.name("target_url")).click();
		// 32 | click | id=newTrackingPath |
		driver.findElement(By.id("newTrackingPath")).click();
		// 33 | type | id=newTrackingPath | benefits
		driver.findElement(By.id("newTrackingPath")).sendKeys("benefits");
		// 34 | click | name=create_tracking |
		driver.findElement(By.name("create_tracking")).click();
		// 35 | click | css=.w-100:nth-child(1) |
		driver.findElement(By.cssSelector(".w-100:nth-child(1)")).click();
		// 36 | click | css=.modal__inner > .fas |
		driver.findElement(By.cssSelector(".modal__inner > .fas")).click();
		// 37 | click | css=.mb-4 > .secondary-btn:nth-child(2) |
		driver.findElement(By.cssSelector(".mb-4 > .secondary-btn:nth-child(2)")).click();
		// 38 | click | css=.w-49:nth-child(1) |
		driver.findElement(By.cssSelector(".w-49:nth-child(1)")).click();
		// 39 | select | css=.w-49:nth-child(1) | label=Import
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".w-49:nth-child(1)"));
			dropdown.findElement(By.xpath("//option[. = 'Import']")).click();
		}
		// 40 | click | css=.w-49:nth-child(1) |
		driver.findElement(By.cssSelector(".w-49:nth-child(1)")).click();
		// 41 | click | css=.d-flex:nth-child(2) |
		driver.findElement(By.cssSelector(".d-flex:nth-child(2)")).click();
		// 42 | select | css=.d-flex:nth-child(2) | label=Button
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".d-flex:nth-child(2)"));
			dropdown.findElement(By.xpath("//option[. = 'Button']")).click();
		}
		// 43 | click | css=.d-flex:nth-child(2) |
		driver.findElement(By.cssSelector(".d-flex:nth-child(2)")).click();
		// 44 | click | id=newTrackingName |
		driver.findElement(By.id("newTrackingName")).click();
		// 45 | type | id=newTrackingName | Button
		driver.findElement(By.id("newTrackingName")).sendKeys("Button");
		// 46 | click | id=newTrackingDescription |
		driver.findElement(By.id("newTrackingDescription")).click();
		// 47 | type | id=newTrackingDescription | Import
		driver.findElement(By.id("newTrackingDescription")).sendKeys("Import");
		// 48 | click | name=create_tracking |
		driver.findElement(By.name("create_tracking")).click();
		// 49 | click | css=.fa-times |
		driver.findElement(By.cssSelector(".fa-times")).click();
		// 50 | click | css=.router-link-active:nth-child(1) > span |
		driver.findElement(By.cssSelector(".router-link-active:nth-child(1) > span")).click();
		// 51 | runScript | window.scrollTo(0,0) |
		js.executeScript("window.scrollTo(0,0)");
		// 52 | click | css=.campaign-row:nth-child(1) span |
		driver.findElement(By.cssSelector(".campaign-row:nth-child(1) span")).click();
		// 53 | click | css=.options > .solid:nth-child(1) |
		driver.findElement(By.cssSelector(".options > .solid:nth-child(1)")).click();
		// 54 | click | id=editName |
		driver.findElement(By.id("editName")).click();
		// 55 | type | id=editName | wapstry
		driver.findElement(By.id("editName")).sendKeys("wapstry");
		// 56 | click | css=.primary-btn:nth-child(2) |
		driver.findElement(By.cssSelector(".primary-btn:nth-child(2)")).click();
		// 57 | click | css=.fa-times |
		driver.findElement(By.cssSelector(".fa-times")).click();
		// 58 | click | css=.campaign-row:nth-child(1) .fa-square |
		driver.findElement(By.cssSelector(".campaign-row:nth-child(1) .fa-square")).click();
		// 59 | click | name=report |
		driver.findElement(By.name("report")).click();
		// 60 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 61 | select | id=reportType | label=Detail Report
		{
			WebElement dropdown = driver.findElement(By.id("reportType"));
			dropdown.findElement(By.xpath("//option[. = 'Detail Report']")).click();
		}
		// 62 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 63 | click | id=startDate |
		driver.findElement(By.id("startDate")).click();
		// 64 | click | css=.mb-1 .vdp-datepicker__calendar > div > .cell:nth-child(13)
		// |
		driver.findElement(By.cssSelector(".mb-1 .vdp-datepicker__calendar > div > .cell:nth-child(13)")).click();
		// 65 | click | id=endDate |
		driver.findElement(By.id("endDate")).click();
		// 66 | click | css=.date-group__item:nth-child(3) .today |
		driver.findElement(By.cssSelector(".date-group__item:nth-child(3) .today")).click();
		// 67 | click | css=.primary-btn:nth-child(4) |
		driver.findElement(By.cssSelector(".primary-btn:nth-child(4)")).click();
		// 68 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 69 | select | id=reportType | label=Summary Report
		{
			WebElement dropdown = driver.findElement(By.id("reportType"));
			dropdown.findElement(By.xpath("//option[. = 'Summary Report']")).click();
		}
		// 70 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 71 | click | css=.primary-btn:nth-child(4) |
		driver.findElement(By.cssSelector(".primary-btn:nth-child(4)")).click();
		// 72 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 73 | select | id=reportType | label=Ineligible Leads
		{
			WebElement dropdown = driver.findElement(By.id("reportType"));
			dropdown.findElement(By.xpath("//option[. = 'Ineligible Leads']")).click();
		}
		// 74 | click | id=reportType |
		driver.findElement(By.id("reportType")).click();
		// 75 | click | css=.primary-btn:nth-child(4) |
		driver.findElement(By.cssSelector(".primary-btn:nth-child(4)")).click();
		// 76 | click | css=.fa-times |
		driver.findElement(By.cssSelector(".fa-times")).click();
		// 77 | click | css=.mb-0 > .fas |
		driver.findElement(By.cssSelector(".mb-0 > .fas")).click();
		// 78 | click | css=.campaign-row:nth-child(1) span |
		driver.findElement(By.cssSelector(".campaign-row:nth-child(1) span")).click();
		// 79 | click | css=.mb-4 > .secondary-btn:nth-child(3) |
		driver.findElement(By.cssSelector(".mb-4 > .secondary-btn:nth-child(3)")).click();
		// 80 | click | css=a:nth-child(1) > .secondary-btn |
		driver.findElement(By.cssSelector("a:nth-child(1) > .secondary-btn")).click();
		// 81 | click | id=mediumImport |
		driver.findElement(By.id("mediumImport")).click();
		// 82 | select | id=mediumImport | label=Button
		{
			WebElement dropdown = driver.findElement(By.id("mediumImport"));
			dropdown.findElement(By.xpath("//option[. = 'Button']")).click();
		}
		// 83 | click | id=mediumImport |
		driver.findElement(By.id("mediumImport")).click();
		// 84 | click | css=.dz-default > span |
		driver.findElement(By.cssSelector(".dz-default > span")).click();
		// 85 | close | |
		driver.close();
	}
}
